DROP TRIGGER IF EXISTS insertValidation;
DELIMITER $
CREATE TRIGGER insertValidation BEFORE INSERT ON STUDENT FOR EACH ROW
BEGIN
	IF DAYNAME(NOW()) = 'Sunday' THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'Cannot enter on sunday stupid...';
	END IF;
END $
DELIMITER ;